CDW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'), name='api'),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('', include('Main.urls'), name="Main"),
)

Main/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    path('', views.enter_page, name='enter_page'),
    path('recovery/', views.recovery_page, name='recovery_page'),
    path('sign_in/', views.sign_in_page, name='sign_in_page'),
    path('sign_up/', views.sign_up_page, name='sign_up_page'),
    path('lk/<int:pk>', views.lk, name='lk'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('lk/edit_profile/<int:pk>', views.edit_profile_page, name='edit_profile_page'),
    path('companies/', views.companies, name='companies'),
    path('change_lang/', views.change_lang, name='change_lang'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

Main/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings
from django.contrib.auth.models import AbstractUser


# Create your models here.

class Industry(models.Model):
    CHOICES = (
        (0, 'Food'),
        (1, 'Finance'),
        (2, 'IT'),
    )

    name = models.IntegerField(
        choices=CHOICES,
    )

    def __str__(self):
        return self.CHOICES[self.name][1]


class User(models.Model):
    STATUS_VARS = [
        (1, 'Visitor'),
        (2, 'User'),
        (3, 'Premium'),
        (4, 'Vip'),
        (4, 'Admin'),
    ]

    CURRENCY_VARS = (
        (1, "EUR"),
        (2, 'USD'),
        (3, 'RUB'),
    )

    COUNTRY_VARS = (
        (1, "Russia"),
        (2, 'USA'),
        (3, 'Italy'),
        (3, 'Germany'),
    )

    email = models.EmailField(unique=True, default='')
    password = models.CharField(max_length=50, default='')
    company = models.CharField(max_length=100, default='', blank=True)
    country = models.IntegerField(choices=COUNTRY_VARS, default=1)
    address = models.CharField(max_length=150, default='', blank=True)
    zipcode = models.CharField(max_length=20, default='', blank=True)
    city = models.CharField(max_length=20, default='', blank=True)
    phone_1 = models.CharField(max_length=20, default='', blank=True)
    phone_2 = models.CharField(max_length=20, default='', blank=True)
    website = models.CharField(max_length=50, default='', blank=True)
    firstname = models.CharField(max_length=50, default='', blank=True)
    lastname = models.CharField(max_length=50, default='', blank=True)
    post = models.CharField(max_length=50, default='', blank=True)
    industry = models.ManyToManyField(Industry, blank=True)
    currency = models.IntegerField(choices=CURRENCY_VARS, default=1)
    is_business = models.BooleanField(default=False)
    balance = models.FloatField(default=0)
    status = models.IntegerField(choices=STATUS_VARS, default=1)
    views_count = models.PositiveIntegerField(default=0)
    description = models.TextField(default='Hi!, Welcome to my IBCA page!')
    created_at = models.DateTimeField(auto_now_add=True)
    token = models.CharField(max_length=64, default='', blank=True)
    is_verified = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return self.firstname + " " + self.lastname + f" ({self.company})"


class ViewNote(models.Model):
    ip = models.GenericIPAddressField(max_length=50)
    user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.ip} ({self.user_id})"

Main/forms.py
from django import forms
from django.forms import widgets
from django.forms.widgets import Widget
from .models import User, Industry
from django.forms import ModelForm


class SignInForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']

        widgets = {
            'email': forms.TextInput(attrs={'class': 'sign_in_forms'}),
            'password': forms.TextInput(attrs={'class': 'sign_in_forms'}),
        }


class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']


class EditProfileForm(ModelForm):

    #industry = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Industry.objects,
    #                                          to_field_name='name')
    class Meta:
        model = User
        fields = ['phone_1', 'phone_2', 'website', 'post', 'firstname', 'lastname', 'industry',
                  'currency', 'description', 'company', 'email', 'country', 'address', 'zipcode']

        #industry = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Industry.objects.all(), to_field_name='name')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Email'}),
            'password': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Password'}),
            'company': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Company'}),
            'firstname': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Firstname'}),
            'lastname': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Lastname'}),
            'phone_1': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Phone number'}),
            'phone_2': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': '(Add.) Phone number'}),
            'website': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Website'}),
            'post': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Post'}),
            'country': forms.Select(attrs={'class': 'edit_profile_form', 'label': 'Country'}),
            'currency': forms.Select(attrs={'class': 'edit_profile_form', 'label': 'Currency'}, choices=User.CURRENCY_VARS),
            'address': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Address'}),
            'zipcode': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Zipcode'}),
            'description': forms.Textarea(attrs={'class': 'edit_profile_form_textarea', 'label': 'Description'}),
            'industry': forms.CheckboxSelectMultiple(choices=Industry.CHOICES)
            #'industry' : forms.SelectMultiple(queryset=None)
        }


class FilterUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['country', 'industry', 'company']

        widgets = {
            'country': forms.Select(attrs={'class': 'edit_profile_form', 'label': 'Country'}),
            'industry': forms.Select(attrs={'class': 'edit_profile_form', 'label': 'Currency'}, choices=Industry.CHOICES),
            'company': forms.TextInput(attrs={'class': 'edit_profile_form', 'label': 'Company'}),
        }

Main/views.py
import json

from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from .models import User, Industry, ViewNote
from .forms import SignInForm, SignUpForm, EditProfileForm, FilterUserForm
from api.serializers import UserSerializer, IndustrySerializer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F
from django.conf import settings
from django.utils.translation import gettext as _
from rest_framework.response import Response
from rest_framework import status
import requests

# Create your views here.

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def enter_page(request):
    # if 'lang' not in request.session:
    #     request.session['lang'] = 'EN'

    context = {'is_authorized': False}
    if 'email' in request.session:
        context['is_authorized'] = True
        user = User.objects.get(email=request.session['email'])
        context['user'] = user

        is_owner = False
        if request.session['email'] == user.email:
            is_owner = True

    return render(request, 'index.html', context)


def sign_in_page(request):
    form = SignInForm()
    context = {'form': form}
    return render(request, 'sign_in_page.html', context)


def sign_up_page(request):
    form = SignUpForm()
    context = {'form': form}
    return render(request, 'sign_up_page.html', context)


def recovery_page(request):
    return render(request, 'recovery.html', context={})


def lk(request, pk):

    user = User.objects.get(id=pk)

    is_owner = False
    is_authorized = False

    if 'email' in request.session:
        is_authorized = True
        if request.session['email'] == user.email:
            is_owner = True

    user_ip = get_client_ip(request)
    try:
        note = ViewNote.objects.get(ip=user_ip, user_id=user.id)
    except:
        User.objects.filter(id=user.id).update(views_count=F("views_count") + 1)
        note = ViewNote.objects.create(ip=user_ip, user_id=user)
        note.save()

    context = {'user': user, 'is_owner': is_owner, 'is_authorized': is_authorized}

    return render(request, 'lk.html', context)


def sign_out(request):
    if 'email' in request.session:
        del request.session['email']

    return redirect("/")


def edit_profile_page(request, pk):
    user = User.objects.get(id=pk)
    serializer = UserSerializer(user)
    form = EditProfileForm(instance=user)
    is_owner = False
    is_authorized = False

    if 'email' in request.session:
        is_authorized = True
        if request.session['email'] == user.email:
            is_owner = True

    context = {'user': user, 'form': form, 'is_owner': is_owner, 'is_authorized': is_authorized}

    if is_owner:
        return render(request, 'edit_profile.html', context)
    else:
        return redirect("/")


def companies(request):
    users = User.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(users, 2)

    user_form = FilterUserForm()

    is_owner = False
    is_authorized = False

    if 'email' in request.session:
        is_authorized = True
        user = User.objects.get(email=request.session['email'])
        # if user:
        #     is_owner = True
    else:
        user = None

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'all_company.html', {'users': users, 'is_owner': is_owner, 'user': user, 'is_authorized': is_authorized, 'form' : user_form})


def change_lang(request):
    lang = dict(request.POST)['lang'][0]

    request.session['lang'] = lang

    return HttpResponse(
        json.dumps({}),
        content_type="application/json")

Main/templates/Main/all_company.html
{%extends "Main/base.html"%}
{%load static%}
{% load i18n%}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}IBCA | {% trans 'All companies' %}{% endblock %}</title>
</head>
<body>
    {% block pagecontent %}
        <br>
        <br>
        <br>
        <br>
        <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <i class="fa fa-filter" style="float: right; font-size: 36px; color: #6274DA; margin-right: 2%; cursor: pointer" onclick="open_filter_board()"></i>
                <br>
                <br>
                <div id="filter_board" style="display: none">
                    <form id="filter_form" style="width: 80%; margin-left: 10%" method="get" action="/api/users/">
                        {% csrf_token %}
                        <div class="row" >
                            <!---company, industry, country--->
                            <div class="col-md-3">
                                <div style="display: inline-block; float: left;">
                                    <span style="margin-right: 10px; font-size: 20px">{% trans 'Name' %}:</span> {{ form.company }}
                                </div>

                            </div>
                            <div class="col-md-2">
                                 <div style="display: inline-block; float: left;">
                                     <span style="margin-right: 10px; font-size: 20px">{% trans 'Industry' %}:</span> {{ form.industry }}
                                 </div>
                            </div>
                            <div class="col-md-2">
                                 <div style="display: inline-block; float: left;">
                                     <span style="margin-right: 10px; font-size: 20px">{% trans 'Country' %}:</span> {{ form.country }}
                                 </div>
                            </div>
                            <div class="col-md-5">
                                <div style="display: inline-block; float: right;">
{#                                    <i class="fa fa-check" style="font-size: 36px; color: green; margin-right: 10px; cursor: pointer;"></i>#}
                                    <input type="submit" value="{% trans 'Send' %}" class="accept_filter">
                                    <i class="fa fa-times" style="font-size: 36px; color: red; cursor: pointer" onclick="close_filter_board()"></i>
                                 </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        </div>
        <div class="data_list" style="height: 100vh; " id="companies_list">
            {% for user in users %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="company_block" action="/lk/{{ user.id }}">

                        <span style="font-size: 18px">
                            {% if user.is_business == True %}
                                {{ user.company }} {% trans 'Business acc.' %} <span style="float: right">{{ user.get_status_display }}, {% trans 'Views' %}: {{ user.views_count }}</span>
                            {% else %}
                                {{ user.firstname }} {{ user.lastname }} ({{ user.company }}) {% trans 'Personal acc.' %} <span style="float: right">{{ user.get_status_display }}, {% trans 'Views' %}: {{ user.views_count }}</span>
                            {% endif %}
                        </span>
                            <hr>
                            {% for ind in user.industry.all %}
                                #{{ ind }}
                            {% endfor %} {% trans 'in' %} {{ user.get_country_display }}
                        <br>
                        <br>
                        {% trans 'Email' %}: {{ user.email }}<br>
                        {% trans 'Website' %}: <a href="{{ user.website }}">{{ user.website }}</a><br><br>
                        {{ user.description }} <span style="float: right">{{ user.created_at }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
    {% if users.has_other_pages %}
        <ul class="pagination">
            {% if users.has_previous %}
              <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in users.paginator.page_range %}
              {% if users.number == i %}
                <li class="active" style="font-size: 24px; background-color: transparent"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if users.has_next %}
              <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
                </div>


    <div id="Modal" class="modal">
      <div class="modal-content" style="background-color: rgb(252, 252, 252);">
              <span class="close" onclick="CloseModal()">&times;</span>
          <div id="ModalTitle">
    
          </div>
          <hr>
          <div id="ModalBody">
    
          </div>
          <div id="ModalButtons">
    
          </div>
      </div>
    </div>

        <script>
             $("#filter_form").submit(function () {
             event.preventDefault();
             console.log($(this).attr('action'), $(this).attr('method'), $(this).serialize());
             csrf_token = $('input[name="csrfmiddlewaretoken"]').val();
             $.ajax({
                 data: $(this).serialize(),
                 headers: {'X-CSRFToken': csrf_token},
                 type: $(this).attr('method'),
                 url: $(this).attr('action'),

                 success: function (response) {
                     console.log(response);

                     let data_place = document.getElementById("companies_list");
                     data_place.innerHTML = '';

                     response.forEach((f_user)=>{
                         data_place.innerHTML += `
                             <div class="row">
                                <div class="col-md-12">
                                    <div class="company_block" onclick="open_profile('/lk/${f_user.id}')" action="/lk/${f_user.id}">
                                        <span style="font-size: 18px">
                                            {% if f_user.is_business == True %}
                                                ${f_user.company} {% trans 'Business acc.' %} <span style="float: right">{% trans 'Views' %}: ${ f_user.views_count }</span>
                                            {% else %}
                                                ${ f_user.firstname } ${ f_user.lastname } (${ f_user.company }) {% trans 'Personal acc.' %} <span style="float: right">{% trans 'Views' %}: ${ f_user.views_count }</span>
                                            {% endif %}
                                        </span>
                                        <hr>
                                        <br>
                                        <br>
                                        {% trans 'Email' %}: ${ f_user.email }<br>
                                        {% trans 'Website' %}: <a href="${ f_user.website }">${ f_user.website }</a><br><br>
                                        ${ f_user.description }
                                    </div>
                                    </div>
                                </div>
                             </div>
                         `;
                     })

                 },
                 error: function (response) {
                     console.log(response);
                     notify("Oops!", "Maybe try one more time...");
                 }
             });
             return false;
             });

             function open_profile(url){
                 console.log(location.href);
                 let address = location.href.replace('/companies/', "");
                 console.log(address);
                 address += url;
                 console.log(address);
                 location.href = address;
             }
        </script>

    {% endblock %}
    {% block lower_links %}{% endblock %}
</body>
</html>

Main/templates/Main/edit_profile.html
{%extends "base.html"%}
{%load static%}
{% load i18n%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}IBCA | {% trans 'Edit profile' %}{% endblock %}</title>
</head>
<body>

 {% block pagecontent %}

        <br>
        <br>
        <br>

        <form id="edit_profile_form" action="/api/users/{{ user.id }}/" method="put">
          {% csrf_token %}
            <div class="row">
                <div class="col-md-4" style="padding-left: 3%;">
                    <h2>{% trans 'Profile' %} ({{ user.get_status_display }})</h2><br>
                    <h6>{% trans 'Personal info' %}</h6>
                    <div class="data_box">
                        {% trans 'Firstname' %}{{ form.firstname }}
                        <hr>
                        {% trans 'Lastname' %}{{ form.lastname }}
                        <hr>
                        {% trans 'Email' %}<span class="edit_profile_span">{{ user.email }}
                        </span>
                        <hr>
                        {% trans 'Phone number' %} {{ form.phone_1 }}
                        <hr>
                        {% trans 'Created at' %} <sapn class="edit_profile_span">{{ user.created_at }}</sapn>
                    </div>
                    <br>
                    <h6>{% trans 'Company info' %}</h6>
                    <div class="data_box">
                        {% trans 'Name' %}{{ form.company }}
                        <hr>
                        {% trans 'Website' %}{{ form.website }}
                        <hr>
                        {% trans 'Industry' %}{{ form.industry }}
                        <hr>
                        {% trans 'Address' %} {{ form.zipcode }} <span class="edit_profile_span"> - </span> {{ form.address }}
                        <hr>
                        {% trans 'Country' %}{{ form.country }}
                        <hr>
                        {% trans 'Currency' %} {{ form.currency }}
                        <hr>
                        {% trans 'Post' %}{{ form.post }}
                        <hr>
                        {% trans 'Contact number' %} {{ form.phone_2 }}
                        <hr>
                        {% trans 'Description' %} {{ form.description }}

                        <br><br>
                        <br><br>
                        <br><br>
                    </div>
                    <br>
                    <input type="submit" value="{% trans 'Commit changes' %}" class="accept_button">
                </div>
                <div class="col-md-8">

                </div>
            </div>
        </form>

     <br>
     <br><br><br>
     <br>
     <br>
     <br><br><br><br><br><br><br><br><br><br><br><br><br><br>



{% endblock %}



</body>
</html>

Main/templates/Main/index.html
{%extends "base.html"%}
{%load static%}
{% load i18n%}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}IBCA | Вход{% endblock %}</title>
</head>
<body>
    {% block pagecontent %}
        {% csrf_token %}
          <!-- <div class="py-5 text-center text-white bg-primary">
            <div class="container py-5"> -->
                <div class="row py-5" align="center">
                    <div class="mx-auto col-lg-10" style="margin-top:10%;">
                        <h1 class="display-4 mb-4 "> {% trans 'International Business Communications Agency' %}</h1>
                            <p class="lead mb-5">{% trans 'The agency is ready to help you connect different countries to achieve the rapid growth of your business' %}.<br>

                                 {% trans 'Any description can be here' %}

                            </p>
                            {% if is_authorized%}
{#                                <a  id="myBtn" class="main_reg" href="sign_in/">Sign in</a>#}
                            {% else %}
                                <a  id="myBtn" class="main_reg" href="sign_up/">{% trans 'Quick start' %}</a>
                            {% endif %}

                    </div>
                </div>
            <!-- </div>
        </div>
     -->
    {% endblock %}
</body>
</html>

Main/templates/Main/lk.html
{%extends "base.html"%}
{%load static%}
{% load i18n%}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}IBCA | {% trans 'Profile' %}{% endblock %}</title>
</head>
<body>
    {% block pagecontent %}

        <br>
        <br>
        <br>

        <div class="row">
            <form id="profile_form">
                <div class="row">
                    <div class="col-md-12">
                        <div class="profile_head" style="text-align: center">
                            <data id="profile_company">
                                {% if user.is_business == True %}
                                    <h1>{{ user.company }}</h1>
                                {% else %}
                                    <h1>{{ user.firstname }} {{ user.lastname }}</h1> <h4>{{ user.post }} {% trans 'in' %} {{ user.company }}</h4>
                                {% endif %}
                            </data>
                            <data id="profile_country" style="display: inline-block">
                                <h6>{{ user.get_country_display }},</h6>
                            </data>
                            <data id="profile_is_business" style="display: inline-block">
                                {% if user.is_business == True %}
                                    <h6>{% trans 'Business acc.' %}</h6>
                                {% else %}
                                    <h6>{% trans 'Personal acc.' %}</h6>
                                {% endif %}
                            </data>
                            <br>
                            {% if is_owner == True %}
                                <data id="profile_balance_currency">
                                {{ user.balance }} ({{ user.get_currency_display }})
                                </data>
                            {% else %}
                            {% endif %}
                            <br>
                            <data id="profile_description">
                                <h6>
                                {% if user.description %}
                                    {{ user.description }}
                                {% else %}
                                    {% trans 'Hi! Welcome to our IBCA page!' %}
                                {% endif %}
                                </h6>
                            </data>

                        </div>

                    </div>
                </div>

                <div class="row" style="text-align: center">
                    <div class="col-md-12">
                        {% for ind in user.industry.all %}
                            #{{ ind }}
                        {% endfor %}
                    </div>
                </div>


                <div class="row" id="profile_footer">
                    <div class="col-md-12">
                        {{ user.email }} <a href={{ user.webiste }}>{{ user.website }}</a><br>
                        {{ user.phone_1 }} {{ user.phone_2 }}<br>
                        {{ user.city}}, {{user.address}}, {{user.zipcode}}
                    </div>
                </div>
            </form>
        </div>

    {% endblock %}
    {% block lower_links %}{% endblock %}
</body>
</html>

Main/templates/Main/sign_in_page.html
{%extends "base.html"%}
{%load static%}
{% load i18n%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}IBCA | {% trans 'Sign in' %}{% endblock %}</title>
</head>
<body>
    {% block pagecontent %}
        <br>
        <br>
        <br>
        <br>
        <br>
<h3 align="center">{% trans 'Enter to your account' %}</h3>
       <form method="post" id="sign_in_form">
        {% csrf_token %}
    <br><br>

    {% trans 'Email' %}
    {{ form.email }}
<br><br>
    {% trans 'Password' %}
    {{ form.password }}
        
    <br><br>
        <input id="sign_up_button" type="submit" value="{% trans 'Send' %}" style="margin-top: 3%;">
        <p align="left" style="font-size: 13px; padding-top: 14px;">{% trans 'Do not have an account yet' %}? <a id="myBtn" href="/sign_up/" >{% trans 'Sign up' %}</a></p>
       <p id="error_message" align="left" style="font-size: 13px; padding-top: 14px; color: #7e0c0c"></p>
   </form>
        <br>
    
    
    {% endblock %}
</body>
</html>

Main/templates/Main/sign_up_page.html
{%extends "base.html"%}
{%load static%}
{% load i18n%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}IBCA | {% trans 'Sign up' %}{% endblock %}</title>
</head>
<body>
    {% block pagecontent %}
        <br>
        <br>
        <br>
        <br>
        <h3 align="center">{% trans 'Registration' %}</h3>
       <form method="post" id="sign_up_form">
            {% csrf_token %}
        <br><br>
        {% trans 'Email' %}
        {{ form.email }}
<br><br>
        {% trans 'Password' %}
        {{ form.password }}
            
        <br><br>
            <input id="sign_up_button" type="submit" value="{% trans 'Send' %}" style="margin-top: 3%;">
            <p align="left" style="font-size: 13px; padding-top: 14px;">{% trans 'Already have an account' %}? <a id="myBtn" href="/sign_in/" >{% trans 'Sign in' %}</a></p>
            <p>{% trans 'By clicking Sign Up, you agree to our Terms, Data Policy and Cookie Policy. You may receive SMS notifications from us and can opt out at any time' %}</p>
            <p id="error_message" align="left" style="font-size: 13px; padding-top: 14px; color: #7e0c0c"></p>
       </form>

       

    {% endblock %}
</body>
</html>